using System;
using System.Collections.Generic;

namespace PSCap
{

    public sealed class PlanetSideMessageType
    {
        private readonly string name;
        private readonly byte opcode;
        private static readonly Dictionary<byte, PlanetSideMessageType> instance = new Dictionary<byte, PlanetSideMessageType>();

        public static readonly PlanetSideMessageType UnknownMessage0 = new PlanetSideMessageType(0, "UnknownMessage0");
        public static readonly PlanetSideMessageType UnknownMessage1 = new PlanetSideMessageType(1, "UnknownMessage1");
        public static readonly PlanetSideMessageType LoginRespMessage = new PlanetSideMessageType(2, "LoginRespMessage");
        public static readonly PlanetSideMessageType UnknownMessage3 = new PlanetSideMessageType(3, "UnknownMessage3");
        public static readonly PlanetSideMessageType ConnectToWorldMessage = new PlanetSideMessageType(4, "ConnectToWorldMessage");
        public static readonly PlanetSideMessageType UnknownLoginMessage5 = new PlanetSideMessageType(5, "UnknownLoginMessage5");
        public static readonly PlanetSideMessageType UnknownMessage6 = new PlanetSideMessageType(6, "UnknownMessage6");
        public static readonly PlanetSideMessageType UnknownMessage7 = new PlanetSideMessageType(7, "UnknownMessage7");
        public static readonly PlanetSideMessageType PlayerStateMessage = new PlanetSideMessageType(8, "PlayerStateMessage");
        public static readonly PlanetSideMessageType UnknownMessage9 = new PlanetSideMessageType(9, "UnknownMessage9");
        public static readonly PlanetSideMessageType HitHint = new PlanetSideMessageType(10, "HitHint");
        public static readonly PlanetSideMessageType DamageMessage = new PlanetSideMessageType(11, "DamageMessage");
        public static readonly PlanetSideMessageType DestroyMessage = new PlanetSideMessageType(12, "DestroyMessage");
        public static readonly PlanetSideMessageType ReloadMessage = new PlanetSideMessageType(13, "ReloadMessage");
        public static readonly PlanetSideMessageType MountVehicleMsg = new PlanetSideMessageType(14, "MountVehicleMsg");
        public static readonly PlanetSideMessageType DismountVehicleMsg = new PlanetSideMessageType(15, "DismountVehicleMsg");
        public static readonly PlanetSideMessageType UseItemMessage = new PlanetSideMessageType(16, "UseItemMessage");
        public static readonly PlanetSideMessageType UnknownMessage17 = new PlanetSideMessageType(17, "UnknownMessage17");
        public static readonly PlanetSideMessageType ChatMsg = new PlanetSideMessageType(18, "ChatMsg");
        public static readonly PlanetSideMessageType CharacterNoRecordMessage = new PlanetSideMessageType(19, "CharacterNoRecordMessage");
        public static readonly PlanetSideMessageType CharacterInfoMessage = new PlanetSideMessageType(20, "CharacterInfoMessage");
        public static readonly PlanetSideMessageType UnknownMessage21 = new PlanetSideMessageType(21, "UnknownMessage21");
        public static readonly PlanetSideMessageType BindPlayerMessage = new PlanetSideMessageType(22, "BindPlayerMessage");
        public static readonly PlanetSideMessageType UnknownMessage23 = new PlanetSideMessageType(23, "UnknownMessage23");
        public static readonly PlanetSideMessageType ObjectCreateMessage = new PlanetSideMessageType(24, "ObjectCreateMessage");
        public static readonly PlanetSideMessageType ObjectDeleteMessage = new PlanetSideMessageType(25, "ObjectDeleteMessage");
        public static readonly PlanetSideMessageType UnknownMessage26 = new PlanetSideMessageType(26, "UnknownMessage26");
        public static readonly PlanetSideMessageType VehicleStateMessage = new PlanetSideMessageType(27, "VehicleStateMessage");
        public static readonly PlanetSideMessageType FrameVehicleStateMessage = new PlanetSideMessageType(28, "FrameVehicleStateMessage");
        public static readonly PlanetSideMessageType GenericObjectStateMsg = new PlanetSideMessageType(29, "GenericObjectStateMsg");
        public static readonly PlanetSideMessageType UnknownMessage30 = new PlanetSideMessageType(30, "UnknownMessage30");
        public static readonly PlanetSideMessageType ActionResultMessage = new PlanetSideMessageType(31, "ActionResultMessage");
        public static readonly PlanetSideMessageType UnknownMessage32 = new PlanetSideMessageType(32, "UnknownMessage32");
        public static readonly PlanetSideMessageType ActionProgressMessage = new PlanetSideMessageType(33, "ActionProgressMessage");
        public static readonly PlanetSideMessageType ActionCancelMessage = new PlanetSideMessageType(34, "ActionCancelMessage");
        public static readonly PlanetSideMessageType ActionCancelAcknowledgeMessage = new PlanetSideMessageType(35, "ActionCancelAcknowledgeMessage");
        public static readonly PlanetSideMessageType SetEmpireMessage = new PlanetSideMessageType(36, "SetEmpireMessage");
        public static readonly PlanetSideMessageType EmoteMsg = new PlanetSideMessageType(37, "EmoteMsg");
        public static readonly PlanetSideMessageType UnuseItemMessage = new PlanetSideMessageType(38, "UnuseItemMessage");
        public static readonly PlanetSideMessageType ObjectDetachMessage = new PlanetSideMessageType(39, "ObjectDetachMessage");
        public static readonly PlanetSideMessageType CreateShortcutMessage = new PlanetSideMessageType(40, "CreateShortcutMessage");
        public static readonly PlanetSideMessageType ChangeShortcutBankMessage = new PlanetSideMessageType(41, "ChangeShortcutBankMessage");
        public static readonly PlanetSideMessageType ObjectAttachMessage = new PlanetSideMessageType(42, "ObjectAttachMessage");
        public static readonly PlanetSideMessageType UnknownMessage43 = new PlanetSideMessageType(43, "UnknownMessage43");
        public static readonly PlanetSideMessageType PlanetsideAttributeMessage = new PlanetSideMessageType(44, "PlanetsideAttributeMessage");
        public static readonly PlanetSideMessageType UnknownMessage45 = new PlanetSideMessageType(45, "UnknownMessage45");
        public static readonly PlanetSideMessageType UnknownMessage46 = new PlanetSideMessageType(46, "UnknownMessage46");
        public static readonly PlanetSideMessageType UnknownMessage47 = new PlanetSideMessageType(47, "UnknownMessage47");
        public static readonly PlanetSideMessageType UnknownMessage48 = new PlanetSideMessageType(48, "UnknownMessage48");
        public static readonly PlanetSideMessageType LoadMapMessage = new PlanetSideMessageType(49, "LoadMapMessage");
        public static readonly PlanetSideMessageType PlayerAvatarChangedMessage = new PlanetSideMessageType(50, "PlayerAvatarChangedMessage");
        public static readonly PlanetSideMessageType ObjectHeldMessage = new PlanetSideMessageType(51, "ObjectHeldMessage");
        public static readonly PlanetSideMessageType WeaponFireMessage = new PlanetSideMessageType(52, "WeaponFireMessage");
        public static readonly PlanetSideMessageType UnknownMessage53 = new PlanetSideMessageType(53, "UnknownMessage53");
        public static readonly PlanetSideMessageType UnknownMessage54 = new PlanetSideMessageType(54, "UnknownMessage54");
        public static readonly PlanetSideMessageType UnknownMessage55 = new PlanetSideMessageType(55, "UnknownMessage55");
        public static readonly PlanetSideMessageType InventoryStateMessage = new PlanetSideMessageType(56, "InventoryStateMessage");
        public static readonly PlanetSideMessageType UnknownMessage57 = new PlanetSideMessageType(57, "UnknownMessage57");
        public static readonly PlanetSideMessageType ChangeFireStateMessage = new PlanetSideMessageType(58, "ChangeFireStateMessage");
        public static readonly PlanetSideMessageType UnknownMessage59 = new PlanetSideMessageType(59, "UnknownMessage59");
        public static readonly PlanetSideMessageType UnknownMessage60 = new PlanetSideMessageType(60, "UnknownMessage60");
        public static readonly PlanetSideMessageType QuantityUpdateMessage = new PlanetSideMessageType(61, "QuantityUpdateMessage");
        public static readonly PlanetSideMessageType ArmorChangedMessage = new PlanetSideMessageType(62, "ArmorChangedMessage");
        public static readonly PlanetSideMessageType ProjectileStateMessage = new PlanetSideMessageType(63, "ProjectileStateMessage");
        public static readonly PlanetSideMessageType MountVehicleCargoMsg = new PlanetSideMessageType(64, "MountVehicleCargoMsg");
        public static readonly PlanetSideMessageType DismountVehicleCargoMsg = new PlanetSideMessageType(65, "DismountVehicleCargoMsg");
        public static readonly PlanetSideMessageType CargoMountPointStatusMessage = new PlanetSideMessageType(66, "CargoMountPointStatusMessage");
        public static readonly PlanetSideMessageType BeginZoningMessage = new PlanetSideMessageType(67, "BeginZoningMessage");
        public static readonly PlanetSideMessageType UnknownMessage68 = new PlanetSideMessageType(68, "UnknownMessage68");
        public static readonly PlanetSideMessageType ItemTransactionResultMessage = new PlanetSideMessageType(69, "ItemTransactionResultMessage");
        public static readonly PlanetSideMessageType ChangeFireModeMessage = new PlanetSideMessageType(70, "ChangeFireModeMessage");
        public static readonly PlanetSideMessageType ChangeAmmoMessage = new PlanetSideMessageType(71, "ChangeAmmoMessage");
        public static readonly PlanetSideMessageType TimeOfDayMessage = new PlanetSideMessageType(72, "TimeOfDayMessage");
        public static readonly PlanetSideMessageType UnknownMessage73 = new PlanetSideMessageType(73, "UnknownMessage73");
        public static readonly PlanetSideMessageType SpawnRequestMessage = new PlanetSideMessageType(74, "SpawnRequestMessage");
        public static readonly PlanetSideMessageType DeployRequestMessage = new PlanetSideMessageType(75, "DeployRequestMessage");
        public static readonly PlanetSideMessageType UnknownMessage76 = new PlanetSideMessageType(76, "UnknownMessage76");
        public static readonly PlanetSideMessageType RepairMessage = new PlanetSideMessageType(77, "RepairMessage");
        public static readonly PlanetSideMessageType ServerVehicleOverrideMsg = new PlanetSideMessageType(78, "ServerVehicleOverrideMsg");
        public static readonly PlanetSideMessageType UnknownMessage79 = new PlanetSideMessageType(79, "UnknownMessage79");
        public static readonly PlanetSideMessageType TargetingInfoMessage = new PlanetSideMessageType(80, "TargetingInfoMessage");
        public static readonly PlanetSideMessageType TriggerEffectMessage = new PlanetSideMessageType(81, "TriggerEffectMessage");
        public static readonly PlanetSideMessageType WeaponDryFireMessage = new PlanetSideMessageType(82, "WeaponDryFireMessage");
        public static readonly PlanetSideMessageType UnknownMessage83 = new PlanetSideMessageType(83, "UnknownMessage83");
        public static readonly PlanetSideMessageType HackMessage = new PlanetSideMessageType(84, "HackMessage");
        public static readonly PlanetSideMessageType DroppodLaunchResponseMessage = new PlanetSideMessageType(85, "DroppodLaunchResponseMessage");
        public static readonly PlanetSideMessageType GenericObjectActionMessage = new PlanetSideMessageType(86, "GenericObjectActionMessage");
        public static readonly PlanetSideMessageType AvatarVehicleTimerMessage = new PlanetSideMessageType(87, "AvatarVehicleTimerMessage");
        public static readonly PlanetSideMessageType AvatarImplantMessage = new PlanetSideMessageType(88, "AvatarImplantMessage");
        public static readonly PlanetSideMessageType UnknownMessage89 = new PlanetSideMessageType(89, "UnknownMessage89");
        public static readonly PlanetSideMessageType DelayedPathMountMsg = new PlanetSideMessageType(90, "DelayedPathMountMsg");
        public static readonly PlanetSideMessageType OrbitalShuttleTimeMsg = new PlanetSideMessageType(91, "OrbitalShuttleTimeMsg");
        public static readonly PlanetSideMessageType UnknownMessage92 = new PlanetSideMessageType(92, "UnknownMessage92");
        public static readonly PlanetSideMessageType UnknownMessage93 = new PlanetSideMessageType(93, "UnknownMessage93");
        public static readonly PlanetSideMessageType UnknownMessage94 = new PlanetSideMessageType(94, "UnknownMessage94");
        public static readonly PlanetSideMessageType FavoritesResponse = new PlanetSideMessageType(95, "FavoritesResponse");
        public static readonly PlanetSideMessageType FavoritesMessage = new PlanetSideMessageType(96, "FavoritesMessage");
        public static readonly PlanetSideMessageType ObjectDetectedMessage = new PlanetSideMessageType(97, "ObjectDetectedMessage");
        public static readonly PlanetSideMessageType UnknownMessage98 = new PlanetSideMessageType(98, "UnknownMessage98");
        public static readonly PlanetSideMessageType SetChatFilterMessage = new PlanetSideMessageType(99, "SetChatFilterMessage");
        public static readonly PlanetSideMessageType AvatarSearchCriteriaMessage = new PlanetSideMessageType(100, "AvatarSearchCriteriaMessage");
        public static readonly PlanetSideMessageType AvatarSearchResponse = new PlanetSideMessageType(101, "AvatarSearchResponse");
        public static readonly PlanetSideMessageType WeaponJammedMessage = new PlanetSideMessageType(102, "WeaponJammedMessage");
        public static readonly PlanetSideMessageType LinkDeadAwarenessMsg = new PlanetSideMessageType(103, "LinkDeadAwarenessMsg");
        public static readonly PlanetSideMessageType DroppodFreefallingMessage = new PlanetSideMessageType(104, "DroppodFreefallingMessage");
        public static readonly PlanetSideMessageType AvatarFirstTimeEventMessage = new PlanetSideMessageType(105, "AvatarFirstTimeEventMessage");
        public static readonly PlanetSideMessageType AggravatedDamageMessage = new PlanetSideMessageType(106, "AggravatedDamageMessage");
        public static readonly PlanetSideMessageType TriggerSoundMessage = new PlanetSideMessageType(107, "TriggerSoundMessage");
        public static readonly PlanetSideMessageType UnknownMessage108 = new PlanetSideMessageType(108, "UnknownMessage108");
        public static readonly PlanetSideMessageType UnknownMessage109 = new PlanetSideMessageType(109, "UnknownMessage109");
        public static readonly PlanetSideMessageType UnknownMessage110 = new PlanetSideMessageType(110, "UnknownMessage110");
        public static readonly PlanetSideMessageType SquadMembershipResponse = new PlanetSideMessageType(111, "SquadMembershipResponse");
        public static readonly PlanetSideMessageType SquadMemberEvent = new PlanetSideMessageType(112, "SquadMemberEvent");
        public static readonly PlanetSideMessageType PlatoonEvent = new PlanetSideMessageType(113, "PlatoonEvent");
        public static readonly PlanetSideMessageType UnknownMessage114 = new PlanetSideMessageType(114, "UnknownMessage114");
        public static readonly PlanetSideMessageType FriendsResponse = new PlanetSideMessageType(115, "FriendsResponse");
        public static readonly PlanetSideMessageType TriggerEnvironmentalDamageMessage = new PlanetSideMessageType(116, "TriggerEnvironmentalDamageMessage");
        public static readonly PlanetSideMessageType TrainingZoneMessage = new PlanetSideMessageType(117, "TrainingZoneMessage");
        public static readonly PlanetSideMessageType DeployableObjectsInfoMessage = new PlanetSideMessageType(118, "DeployableObjectsInfoMessage");
        public static readonly PlanetSideMessageType SquadState = new PlanetSideMessageType(119, "SquadState");
        public static readonly PlanetSideMessageType OxygenStateMessage = new PlanetSideMessageType(120, "OxygenStateMessage");
        public static readonly PlanetSideMessageType TradeMessage = new PlanetSideMessageType(121, "TradeMessage");
        public static readonly PlanetSideMessageType UnknownMessage122 = new PlanetSideMessageType(122, "UnknownMessage122");
        public static readonly PlanetSideMessageType DamageFeedbackMessage = new PlanetSideMessageType(123, "DamageFeedbackMessage");
        public static readonly PlanetSideMessageType UnknownMessage124 = new PlanetSideMessageType(124, "UnknownMessage124");
        public static readonly PlanetSideMessageType UnknownMessage125 = new PlanetSideMessageType(125, "UnknownMessage125");
        public static readonly PlanetSideMessageType UnknownMessage126 = new PlanetSideMessageType(126, "UnknownMessage126");
        public static readonly PlanetSideMessageType AvatarStatisticsMessage = new PlanetSideMessageType(127, "AvatarStatisticsMessage");
        public static readonly PlanetSideMessageType GenericObjectAction2Message = new PlanetSideMessageType(128, "GenericObjectAction2Message");
        public static readonly PlanetSideMessageType DestroyDisplayMessage = new PlanetSideMessageType(129, "DestroyDisplayMessage");
        public static readonly PlanetSideMessageType TriggerBotAction = new PlanetSideMessageType(130, "TriggerBotAction");
        public static readonly PlanetSideMessageType UnknownMessage131 = new PlanetSideMessageType(131, "UnknownMessage131");
        public static readonly PlanetSideMessageType SquadWaypointEvent = new PlanetSideMessageType(132, "SquadWaypointEvent");
        public static readonly PlanetSideMessageType OffshoreVehicleMessage = new PlanetSideMessageType(133, "OffshoreVehicleMessage");
        public static readonly PlanetSideMessageType ObjectDeployedMessage = new PlanetSideMessageType(134, "ObjectDeployedMessage");
        public static readonly PlanetSideMessageType ObjectDeployedCountMessage = new PlanetSideMessageType(135, "ObjectDeployedCountMessage");
        public static readonly PlanetSideMessageType UnknownMessage136 = new PlanetSideMessageType(136, "UnknownMessage136");
        public static readonly PlanetSideMessageType UnknownMessage137 = new PlanetSideMessageType(137, "UnknownMessage137");
        public static readonly PlanetSideMessageType PlayerStasisMessage = new PlanetSideMessageType(138, "PlayerStasisMessage");
        public static readonly PlanetSideMessageType UnknownMessage139 = new PlanetSideMessageType(139, "UnknownMessage139");
        public static readonly PlanetSideMessageType UnknownMessage140 = new PlanetSideMessageType(140, "UnknownMessage140");
        public static readonly PlanetSideMessageType OutfitMembershipResponse = new PlanetSideMessageType(141, "OutfitMembershipResponse");
        public static readonly PlanetSideMessageType UnknownMessage142 = new PlanetSideMessageType(142, "UnknownMessage142");
        public static readonly PlanetSideMessageType OutfitEvent = new PlanetSideMessageType(143, "OutfitEvent");
        public static readonly PlanetSideMessageType OutfitMemberEvent = new PlanetSideMessageType(144, "OutfitMemberEvent");
        public static readonly PlanetSideMessageType OutfitMemberUpdate = new PlanetSideMessageType(145, "OutfitMemberUpdate");
        public static readonly PlanetSideMessageType PlanetsideStringAttributeMessage = new PlanetSideMessageType(146, "PlanetsideStringAttributeMessage");
        public static readonly PlanetSideMessageType DataChallengeMessage = new PlanetSideMessageType(147, "DataChallengeMessage");
        public static readonly PlanetSideMessageType UnknownMessage148 = new PlanetSideMessageType(148, "UnknownMessage148");
        public static readonly PlanetSideMessageType WeatherMessage = new PlanetSideMessageType(149, "WeatherMessage");
        public static readonly PlanetSideMessageType SimDataChallengeResp = new PlanetSideMessageType(150, "SimDataChallengeResp");
        public static readonly PlanetSideMessageType UnknownMessage151 = new PlanetSideMessageType(151, "UnknownMessage151");
        public static readonly PlanetSideMessageType OutfitListEvent = new PlanetSideMessageType(152, "OutfitListEvent");
        public static readonly PlanetSideMessageType EmpireIncentivesMessage = new PlanetSideMessageType(153, "EmpireIncentivesMessage");
        public static readonly PlanetSideMessageType UnknownMessage154 = new PlanetSideMessageType(154, "UnknownMessage154");
        public static readonly PlanetSideMessageType SyncMessage = new PlanetSideMessageType(155, "SyncMessage");
        public static readonly PlanetSideMessageType DebugDrawMessage = new PlanetSideMessageType(156, "DebugDrawMessage");
        public static readonly PlanetSideMessageType SoulMarkMessage = new PlanetSideMessageType(157, "SoulMarkMessage");
        public static readonly PlanetSideMessageType UplinkPositionEvent = new PlanetSideMessageType(158, "UplinkPositionEvent");
        public static readonly PlanetSideMessageType HotSpotUpdateMessage = new PlanetSideMessageType(159, "HotSpotUpdateMessage");
        public static readonly PlanetSideMessageType BuildingInfoUpdateMessage = new PlanetSideMessageType(160, "BuildingInfoUpdateMessage");
        public static readonly PlanetSideMessageType FireHintMessage = new PlanetSideMessageType(161, "FireHintMessage");
        public static readonly PlanetSideMessageType UnknownMessage162 = new PlanetSideMessageType(162, "UnknownMessage162");
        public static readonly PlanetSideMessageType UplinkResponse = new PlanetSideMessageType(163, "UplinkResponse");
        public static readonly PlanetSideMessageType UnknownMessage164 = new PlanetSideMessageType(164, "UnknownMessage164");
        public static readonly PlanetSideMessageType WarpgateResponse = new PlanetSideMessageType(165, "WarpgateResponse");
        public static readonly PlanetSideMessageType DamageWithPositionMessage = new PlanetSideMessageType(166, "DamageWithPositionMessage");
        public static readonly PlanetSideMessageType GenericActionMessage = new PlanetSideMessageType(167, "GenericActionMessage");
        public static readonly PlanetSideMessageType ContinentalLockUpdateMessage = new PlanetSideMessageType(168, "ContinentalLockUpdateMessage");
        public static readonly PlanetSideMessageType AvatarGrenadeStateMessage = new PlanetSideMessageType(169, "AvatarGrenadeStateMessage");
        public static readonly PlanetSideMessageType UnknownMessage170 = new PlanetSideMessageType(170, "UnknownMessage170");
        public static readonly PlanetSideMessageType UnknownMessage171 = new PlanetSideMessageType(171, "UnknownMessage171");
        public static readonly PlanetSideMessageType UnknownMessage172 = new PlanetSideMessageType(172, "UnknownMessage172");
        public static readonly PlanetSideMessageType AvatarDeadStateMessage = new PlanetSideMessageType(173, "AvatarDeadStateMessage");
        public static readonly PlanetSideMessageType CSAssistMessage = new PlanetSideMessageType(174, "CSAssistMessage");
        public static readonly PlanetSideMessageType CSAssistCommentMessage = new PlanetSideMessageType(175, "CSAssistCommentMessage");
        public static readonly PlanetSideMessageType UnknownMessage176 = new PlanetSideMessageType(176, "UnknownMessage176");
        public static readonly PlanetSideMessageType UnknownMessage177 = new PlanetSideMessageType(177, "UnknownMessage177");
        public static readonly PlanetSideMessageType VoiceHostInfo = new PlanetSideMessageType(178, "VoiceHostInfo");
        public static readonly PlanetSideMessageType BattleplanMessage = new PlanetSideMessageType(179, "BattleplanMessage");
        public static readonly PlanetSideMessageType BattleExperienceMessage = new PlanetSideMessageType(180, "BattleExperienceMessage");
        public static readonly PlanetSideMessageType UnknownMessage181 = new PlanetSideMessageType(181, "UnknownMessage181");
        public static readonly PlanetSideMessageType ZonePopulationUpdateMessage = new PlanetSideMessageType(182, "ZonePopulationUpdateMessage");
        public static readonly PlanetSideMessageType DisconnectMessage = new PlanetSideMessageType(183, "DisconnectMessage");
        public static readonly PlanetSideMessageType ExperienceAddedMessage = new PlanetSideMessageType(184, "ExperienceAddedMessage");
        public static readonly PlanetSideMessageType OrbitalStrikeWaypointMessage = new PlanetSideMessageType(185, "OrbitalStrikeWaypointMessage");
        public static readonly PlanetSideMessageType KeepAliveMessage = new PlanetSideMessageType(186, "KeepAliveMessage");
        public static readonly PlanetSideMessageType MapObjectStateBlockMessage = new PlanetSideMessageType(187, "MapObjectStateBlockMessage");
        public static readonly PlanetSideMessageType SnoopMsg = new PlanetSideMessageType(188, "SnoopMsg");
        public static readonly PlanetSideMessageType UnknownMessage189 = new PlanetSideMessageType(189, "UnknownMessage189");
        public static readonly PlanetSideMessageType PlayerStateShiftMessage = new PlanetSideMessageType(190, "PlayerStateShiftMessage");
        public static readonly PlanetSideMessageType ZipLineMessage = new PlanetSideMessageType(191, "ZipLineMessage");
        public static readonly PlanetSideMessageType CaptureFlagUpdateMessage = new PlanetSideMessageType(192, "CaptureFlagUpdateMessage");
        public static readonly PlanetSideMessageType VanuModuleUpdateMessage = new PlanetSideMessageType(193, "VanuModuleUpdateMessage");
        public static readonly PlanetSideMessageType UnknownMessage194 = new PlanetSideMessageType(194, "UnknownMessage194");
        public static readonly PlanetSideMessageType ProximityTerminalUseMessage = new PlanetSideMessageType(195, "ProximityTerminalUseMessage");
        public static readonly PlanetSideMessageType QuantityDeltaUpdateMessage = new PlanetSideMessageType(196, "QuantityDeltaUpdateMessage");
        public static readonly PlanetSideMessageType ChainLashMessage = new PlanetSideMessageType(197, "ChainLashMessage");
        public static readonly PlanetSideMessageType ZoneInfoMessage = new PlanetSideMessageType(198, "ZoneInfoMessage");
        public static readonly PlanetSideMessageType UnknownMessage199 = new PlanetSideMessageType(199, "UnknownMessage199");
        public static readonly PlanetSideMessageType WeaponLazeTargetPositionMessage = new PlanetSideMessageType(200, "WeaponLazeTargetPositionMessage");
        public static readonly PlanetSideMessageType ModuleLimitsMessage = new PlanetSideMessageType(201, "ModuleLimitsMessage");
        public static readonly PlanetSideMessageType OutfitBenefitMessage = new PlanetSideMessageType(202, "OutfitBenefitMessage");
        public static readonly PlanetSideMessageType EmpireChangeTimeMessage = new PlanetSideMessageType(203, "EmpireChangeTimeMessage");
        public static readonly PlanetSideMessageType ClockCalibrationMessage = new PlanetSideMessageType(204, "ClockCalibrationMessage");
        public static readonly PlanetSideMessageType DensityLevelUpdateMessage = new PlanetSideMessageType(205, "DensityLevelUpdateMessage");
        public static readonly PlanetSideMessageType ActOfGodMessage = new PlanetSideMessageType(206, "ActOfGodMessage");
        public static readonly PlanetSideMessageType AvatarAwardMessage = new PlanetSideMessageType(207, "AvatarAwardMessage");
        public static readonly PlanetSideMessageType UnknownMessage208 = new PlanetSideMessageType(208, "UnknownMessage208");
        public static readonly PlanetSideMessageType DisplayedAwardMessage = new PlanetSideMessageType(209, "DisplayedAwardMessage");
        public static readonly PlanetSideMessageType RespawnAMSInfoMessage = new PlanetSideMessageType(210, "RespawnAMSInfoMessage");
        public static readonly PlanetSideMessageType ComponentDamageMessage = new PlanetSideMessageType(211, "ComponentDamageMessage");
        public static readonly PlanetSideMessageType UnknownMessage212 = new PlanetSideMessageType(212, "UnknownMessage212");
        public static readonly PlanetSideMessageType PropertyOverrideMessage = new PlanetSideMessageType(213, "PropertyOverrideMessage");
        public static readonly PlanetSideMessageType WarpgateLinkOverrideMessage = new PlanetSideMessageType(214, "WarpgateLinkOverrideMessage");
        public static readonly PlanetSideMessageType EmpireBenefitsMessage = new PlanetSideMessageType(215, "EmpireBenefitsMessage");
        public static readonly PlanetSideMessageType ForceEmpireMessage = new PlanetSideMessageType(216, "ForceEmpireMessage");
        public static readonly PlanetSideMessageType BroadcastWarpgateUpdateMessage = new PlanetSideMessageType(217, "BroadcastWarpgateUpdateMessage");
        public static readonly PlanetSideMessageType UnknownMessage218 = new PlanetSideMessageType(218, "UnknownMessage218");
        public static readonly PlanetSideMessageType UnknownMessage219 = new PlanetSideMessageType(219, "UnknownMessage219");
        public static readonly PlanetSideMessageType SquadMainTerminalResponseMessage = new PlanetSideMessageType(220, "SquadMainTerminalResponseMessage");
        public static readonly PlanetSideMessageType SquadOrderMessage = new PlanetSideMessageType(221, "SquadOrderMessage");
        public static readonly PlanetSideMessageType UnknownMessage222 = new PlanetSideMessageType(222, "UnknownMessage222");
        public static readonly PlanetSideMessageType ZoneLockInfoMessage = new PlanetSideMessageType(223, "ZoneLockInfoMessage");
        public static readonly PlanetSideMessageType SquadBindInfoMessage = new PlanetSideMessageType(224, "SquadBindInfoMessage");
        public static readonly PlanetSideMessageType AudioSequenceMessage = new PlanetSideMessageType(225, "AudioSequenceMessage");
        public static readonly PlanetSideMessageType SquadFacilityBindInfoMessage = new PlanetSideMessageType(226, "SquadFacilityBindInfoMessage");
        public static readonly PlanetSideMessageType ZoneForcedCavernConnectionsMessage = new PlanetSideMessageType(227, "ZoneForcedCavernConnectionsMessage");
        public static readonly PlanetSideMessageType MissionActionMessage = new PlanetSideMessageType(228, "MissionActionMessage");
        public static readonly PlanetSideMessageType UnknownMessage229 = new PlanetSideMessageType(229, "UnknownMessage229");
        public static readonly PlanetSideMessageType ReplicationStreamMessage = new PlanetSideMessageType(230, "ReplicationStreamMessage");
        public static readonly PlanetSideMessageType SquadDefinitionActionMessage = new PlanetSideMessageType(231, "SquadDefinitionActionMessage");
        public static readonly PlanetSideMessageType SquadDetailDefinitionUpdateMessage = new PlanetSideMessageType(232, "SquadDetailDefinitionUpdateMessage");
        public static readonly PlanetSideMessageType TacticsMessage = new PlanetSideMessageType(233, "TacticsMessage");
        public static readonly PlanetSideMessageType RabbitUpdateMessage = new PlanetSideMessageType(234, "RabbitUpdateMessage");
        public static readonly PlanetSideMessageType SquadInvitationRequestMessage = new PlanetSideMessageType(235, "SquadInvitationRequestMessage");
        public static readonly PlanetSideMessageType CharacterKnowledgeMessage = new PlanetSideMessageType(236, "CharacterKnowledgeMessage");
        public static readonly PlanetSideMessageType GameScoreUpdateMessage = new PlanetSideMessageType(237, "GameScoreUpdateMessage");
        public static readonly PlanetSideMessageType UnknownMessage238 = new PlanetSideMessageType(238, "UnknownMessage238");
        public static readonly PlanetSideMessageType UnknownMessage239 = new PlanetSideMessageType(239, "UnknownMessage239");
        public static readonly PlanetSideMessageType QueueTimedHelpMessage = new PlanetSideMessageType(240, "QueueTimedHelpMessage");
        public static readonly PlanetSideMessageType MailMessage = new PlanetSideMessageType(241, "MailMessage");
        public static readonly PlanetSideMessageType UnknownMessage242 = new PlanetSideMessageType(242, "UnknownMessage242");
        public static readonly PlanetSideMessageType ClientCheatedMessage = new PlanetSideMessageType(243, "ClientCheatedMessage");
        public static readonly PlanetSideMessageType UnknownMessage244 = new PlanetSideMessageType(244, "UnknownMessage244");
        public static readonly PlanetSideMessageType UnknownMessage245 = new PlanetSideMessageType(245, "UnknownMessage245");
        public static readonly PlanetSideMessageType UnknownMessage246 = new PlanetSideMessageType(246, "UnknownMessage246");
        public static readonly PlanetSideMessageType UnknownMessage247 = new PlanetSideMessageType(247, "UnknownMessage247");
        public static readonly PlanetSideMessageType UnknownMessage248 = new PlanetSideMessageType(248, "UnknownMessage248");
        public static readonly PlanetSideMessageType UnknownMessage249 = new PlanetSideMessageType(249, "UnknownMessage249");
        public static readonly PlanetSideMessageType UnknownMessage250 = new PlanetSideMessageType(250, "UnknownMessage250");
        public static readonly PlanetSideMessageType UnknownMessage251 = new PlanetSideMessageType(251, "UnknownMessage251");
        public static readonly PlanetSideMessageType UnknownMessage252 = new PlanetSideMessageType(252, "UnknownMessage252");
        public static readonly PlanetSideMessageType UnknownMessage253 = new PlanetSideMessageType(253, "UnknownMessage253");
        public static readonly PlanetSideMessageType UnknownMessage254 = new PlanetSideMessageType(254, "UnknownMessage254");
        public static readonly PlanetSideMessageType UnknownMessage255 = new PlanetSideMessageType(255, "UnknownMessage255");

        private PlanetSideMessageType(byte opcode, string name)
        {
            this.opcode = opcode;
            this.name = name;
            instance[opcode] = this;
        }

        public override string ToString()
        {
            return name;
        }

        public static explicit operator PlanetSideMessageType(byte opcode)
        {
            PlanetSideMessageType res;

            if (instance.TryGetValue(opcode, out res))
                return res;
            else
                throw new InvalidCastException();
        }
    }
}